services:
  portfolio:
    privileged: true
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      target: frontend-prod
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    volumes:
      - frontend_modules:/usr/portfolio/node_modules
volumes:
  frontend_modules:
